### ISSUE TITLE
error when used with restricted access rights

### ISSUE THREAD

**Issue by slawo** [boz/kail#12]
When I try to use kail to get logs from an svc I get this error:
```
./kail --ns=ns1 --context=dev  --svc=projector
kail: error: Can't connnect to kubernetes: namespaces is forbidden: User "..." cannot list namespaces at the cluster scope
```

It seems like kail tries to list namespaces despite being given a precise namespace and svc.

Am I missing something?

**Comment by boz** [comment]
Yeah it does not push down all of the constraints (you might add another `--ns` flag, for instance).

Try using
```sh
./kail --context=dev  --svc=ns1/projector
```

**Comment by boz** [comment]
@slawo let me know if the workaround solves the issue.  Thanks for the report!

**Comment by boz** [comment]
Hey @wsargent.  Long time no see!  Hope you're doing well.

Did you try the workaround I posted?

```sh
kail --pod=my-namespace/mah-pod
```

**Comment by wsargent** [comment]
Oh hi Adam!

Same deal with namespace/mah-pod -- "cannot list pods at the cluster scope  cmp=lister" and the same error with "cmp=controller"

**Comment by boz** [comment]
Thanks @wsargent!  I'll take a look at this when I can.

**Comment by ngauje** [comment]
Same problem here when using Kail on an Openshift cluster :
`kail: error: Can't connnect to kubernetes: namespaces is forbidden: User "stduser" cannot list namespaces at the cluster scope: User "stduser" cannot list all namespaces in the cluster`

**Comment by b3zn0gim** [comment]
Looks like in later versions situation become even worse. I want my teams to be able to read logs this way:
```
kail -n personal-namespace -l 'app=proxy'
```

I already gave cluster scope permission to read namespaces, but, I think, since last version of kail it also want to read pods at cluster scope and the command above doesn't work anymore. It produces error like:
```
$ kail -n personal-namespace -l 'app=proxy'
ERRO[0000] client list: pods is forbidden: User "system:serviceaccount:default:superhero" cannot list resource "pods" in API group "" at the cluster scope  cmp=lister
```
Even tho user have permissions to read namespaces and to read pods in specified namespace.

I was able to reproduce the same error using command
```
kubectl get pod --all-namespaces
```

I think in latest versions kail was switched to this behaviour and it broke our usual workflow. Now I have to give people clusterscope permission to read all pods in my cluster and that is not something what I to do by any chance.
