### ISSUE TITLE
 consider using krew-release-bot for publishing plugin releases

### ISSUE THREAD

**Issue by rajatjindal** [boz/kail#52]
I have created [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) to auto publish new plugin releases to krew-index repo. 

If its ok with kail authors, I can open a PR to start using that for auto publishing the releases or you can look at the [travis](https://github.com/rajatjindal/krew-release-bot/blob/master/examples/travis.yml) example here, and configure it.

Many thanks for considering.
Rajat Jindal

**Comment by boz** [comment]
Hi @rajatjindal, great project.

I'm considering migrating from Travis to GH Actions, so maybe that can happen at the same time.

If you have time to add the change to kail (either with travis or with gh actions), I'd appreciate it.  Otherwise I can take a look when I get around to moving off of travis.

**Comment by chandanpasunoori** [comment]
fixed https://github.com/boz/kail/pull/83
